spring:
  datasource:
    url: jdbc:mysql://localhost:3306/restaurant
    username: root
    password: 3694
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: 'create-drop'